### ISSUE TITLE
mac如何激活

### ISSUE THREAD

**Issue by wan9xx** [743859910/Typora_Unlocker#5]
按照win的步骤执行发生了错误，是在Contents目录下执行的

**Comment by wan9xx** [comment]
zsh: exec format error: ./node_inject

**Comment by wan9xx** [comment]
> 参考 Linux 版本的试试呢？ 添加执行权限，然后再执行。 chmod +x node_inject ./node_inject

加了权限的

**Comment by wan9xx** [comment]
![image](https://github.com/user-attachments/assets/a1b9964e-5e1d-45a0-a7fc-33f73a188685)

**Comment by Conroy-X** [comment]
> 按照win的步骤执行发生了错误，是在Contents目录下执行的

https://github.com/DiamondHunters/NodeInject_Hook_example
这个破解出处应该是在这里， 别人指明了说不支持mac的

**Comment by wan9xx** [comment]
> > 按照win的步骤执行发生了错误，是在Contents目录下执行的
> 
> https://github.com/DiamondHunters/NodeInject_Hook_example 这个破解出处应该是在这里， 别人指明了说不支持mac的 ![image](https://private-user-images.githubusercontent.com/28860654/355444491-9f3a5133-2386-4f86-9491-b164ec6c9677.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzA5NTAsIm5iZiI6MTcyMzUzMDY1MCwicGF0aCI6Ii8yODg2MDY1NC8zNTU0NDQ0OTEtOWYzYTUxMzMtMjM4Ni00Zjg2LTk0OTEtYjE2NGVjNmM5Njc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA2MzA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NmQzNDRmMTllY2FlMWVjMzlmNjc1ZGMwOWRlNDkyNmIyYjA3ZjM2NTQyZTdiN2M2YmFlOTBhNzgxNjhmNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xY-02nB1eKSs-Sy0daHf8W9X2G4Q7L1V8t9y8vLd1hs)

好吧，那那就没法了
